services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - ml
      - db

  ml:
    build:
      context: ./ml
    image: fashionclip-ml
    container_name: fashionclip-ml
    volumes:
      - ./ml:/app
    working_dir: /app
    command: python main.py test.jpg
    environment:
      - DB_HOST=your_db_host
      - DB_USER=your_db_user
      - DB_PASS=your_db_password
      - DB_NAME=your_db_name
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: digital_wardrobe_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digital_wardrobe
    ports:
      - "5432:5432"
